### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by neonichu** [alcatraz/Alcatraz#116]
I am thinking of doing a simple command line tool which gets the path to a packages.json file and a plugin name as parameters and it will install the given plugin with the existing functionality.

I see two use cases for this:
1. A way to double-check that a new plugin one adds to the packages repo will actually build and install fine with Alcatraz.
2. Possibility to build a shell script which installs a defined set of plugins - would be nice to get a team up and running.

Any thoughts on this?

**Comment by kevinnguy** [comment]
Hi @neonichu this sounds like a great idea! Have you created a repo for your packages script?
