### ISSUE TITLE
Xcode Command Line Tools are not currently installed, and are required to run Alcatraz.

### ISSUE THREAD

**Issue by akring** [alcatraz/Alcatraz#152]
I used Alcatraz on my macbook for a long time,and when I installed it on my iMac today,I met a problem.
I installed this plug-in and select "Package Manager" in "Window" menu.However the alert shows that "Xcode Command Line Tools are not currently installed, and are required to run Alcatraz."
I checked the xcode-peferences-download and I'm quite sure I had installed the Command Line Tools.I even download it from developer support site and installed it again,but it didn't work.

**Comment by irskep** [comment]
I just ran into this, and wouldn't call a symlink a "fix." It's pretty common to have git installed in `/usr/local/bin`...

**Comment by jurre** [comment]
We could maybe check a few paths and make it configurable I suppose? Do you have any other alternatives?

**Comment by irskep** [comment]
Check `$PATH`?

**Comment by you-2-can** [comment]
@nextriot  in the master i can't found this ATZGit.h

**Comment by zhangjikuan** [comment]
不要给我推送了谢谢

发自我的 iPhone

**Comment by nextriot** [comment]
@you-2-can it's in the `helpers` folder
