### ISSUE TITLE
i couldn't install Alcatraz on my mac,but it shows "Alcatraz successfuly installed!!"

### ISSUE THREAD

**Issue by SSCedric** [alcatraz/Alcatraz#192]
i have tried tow way to install Alcatraz,but didn't succeed neither.Here is my question:
1.
i use the command 
curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
and run on my terminal,and then showed
"
x Alcatraz.xcplugin/: Can't create 'Alcatraz.xcplugin'
x Alcatraz.xcplugin/Contents/: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents'
x Alcatraz.xcplugin/Contents/Info.plist: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Info.plist'
x Alcatraz.xcplugin/Contents/MacOS/: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/MacOS'
x Alcatraz.xcplugin/Contents/Resources/: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources'
x Alcatraz.xcplugin/Contents/Resources/en.lproj/: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/en.lproj'
x Alcatraz.xcplugin/Contents/Resources/eye_icon.tiff: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/eye_icon.tiff'
x Alcatraz.xcplugin/Contents/Resources/github_logo.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/github_logo.png'
x Alcatraz.xcplugin/Contents/Resources/github_logo@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/github_logo@2x.png'
x Alcatraz.xcplugin/Contents/Resources/link_icon.tiff: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/link_icon.tiff'
x Alcatraz.xcplugin/Contents/Resources/PluginWindow.nib: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/PluginWindow.nib'
x Alcatraz.xcplugin/Contents/Resources/toolbar_colors.tiff: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_colors.tiff'
x Alcatraz.xcplugin/Contents/Resources/toolbar_plugins.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_plugins.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_plugins.tiff: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_plugins.tiff'
x Alcatraz.xcplugin/Contents/Resources/toolbar_plugins@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_plugins@2x.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_plugins_selected.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_plugins_selected.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_plugins_selected@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_plugins_selected@2x.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_templates.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_templates.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_templates.tiff: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_templates.tiff'
x Alcatraz.xcplugin/Contents/Resources/toolbar_templates@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_templates@2x.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_templates_selected.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_templates_selected.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_templates_selected@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_templates_selected@2x.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_themes.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_themes.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_themes@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_themes@2x.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_themes_selected.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_themes_selected.png'
x Alcatraz.xcplugin/Contents/Resources/toolbar_themes_selected@2x.png: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/toolbar_themes_selected@2x.png'
x Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings'
x Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings'
x Alcatraz.xcplugin/Contents/MacOS/Alcatraz: Failed to create dir 'Alcatraz.xcplugin'Can't create 'Alcatraz.xcplugin/Contents/MacOS/Alcatraz'
100   99k  100   99k    0     0  16351      0  0:00:06  0:00:06 --:--:-- 37551
tar: Error exit delayed from previous errors.
Alcatraz successfuly installed!!1!🍻   Please restart your Xcode.
"
i try command:
sudo  curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
but it also didn't work.

what can i do to fix it?
thanks:)

**Comment by kingkratos** [comment]
thanks ! it‘s helpful to me

**Comment by RMK19** [comment]
Thanks  @kattrali
