### ISSUE TITLE
Alcatraz doesn't work on Xcode 6.2 beta

### ISSUE THREAD

**Issue by rsanchezsaez** [alcatraz/Alcatraz#203]
The `Package Manager` item doesn't seem to show in the `Window` menu.

**Comment by shepting** [comment]
I can confirm that after installing for Xcode-Beta 6.2 that Xcode crashed the first time tapping the menu item. The next time the menu item was gone. But after running the install script again it was there and tappable with no further crashes.

**Comment by almas73** [comment]
just updated to official release of Xcode 6.2. Alcatraz isn't showing up.

**Comment by ianmasters** [comment]
The app store official Xcode 6.2 UUID is A16FF353-8441-459E-A50C-B071F53F51B7.

Add that to the DVTPlugInCompatibilityUUIDs key in all your plugins in:
~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/*plugin.xcplugin*/*Show Package Contents*/Contents/Info.plist

There are scripts floating about to help speed this up or you can write your own. I'll leave that as an exercise for the reader.

For future reference, to get Xcode's UUID, in terminal:
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

**Comment by rmvz3** [comment]
EPIC ANSWER ianmaster \o/

Works like a charm. Thank you!

**Comment by thehellsoul** [comment]
thank ianmaster, works for me as well.

**Comment by chancyWu** [comment]
Thanks for your solution @ianmasters

**Comment by jirasak** [comment]
work like a magic, thanks @ianmasters

**Comment by serejahh** [comment]
It works! Thanks you a lot, @ianmasters

**Comment by fuxx** [comment]
`find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add A16FF353-8441-459E-A50C-B071F53F51B7`

For quick copy paste open your terminal and copy the command above. Searches for info plists recursively and adds the UUID to the UUIDs array.

**Comment by adamwaite** [comment]
@fuxx you beaut. Forgotten how painful Xcode was without Fuzzy autocomplete.

**Comment by clariontools** [comment]
Seems like this was added 2 hours ago to the repo, but an uninstall and reinstall didn't work for me.  Thanks @ianmasters for the UUID and thanxxx @fuxx for the find snippet!

**Comment by jurre** [comment]
@clariontools the script doesn't install from `master`, it installs from `deploy`. I will try to release a new version soon

**Comment by clozach** [comment]
@fuxx Thank you! (And while I'm at it, thank you to the Alcatraz team, any Xcode plugin authors who might see this, and heck, even Google for pointing straight to this thread when I needed it. Everyone is awesome!)

**Comment by bodak** [comment]
@ianmasters fantastic!

**Comment by guyisra** [comment]
:+1: @fuxx

**Comment by iOSSoftwareEngineer** [comment]
Thank you, Stefan!

**Comment by morisk** [comment]
@ianmasters thanks

**Comment by cielpy** [comment]
Thanks @fuxx

**Comment by adamwaite** [comment]
New command for App Store Xcode 6.3:

```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add 9F75337B-21B4-4ADC-B558-F9CADF7073A7
```

Just updated the UDID from fuxx's solution.

**Comment by aroxby** [comment]
For anyone who finds this on Google, here is the command to insert the UUID of whatever XCode version you are using:

    find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add $(defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID)
