### ISSUE TITLE
Can't get Alcatraz to work with Xcode 6.2

### ISSUE THREAD

**Issue by blixt** [alcatraz/Alcatraz#218]
I used Alcatraz with Xcode 6.1 but after I updated to 6.2 today, it's no longer appearing in the Window menu. I tried exiting Xcode and rerunning the install script, but it doesn't seem to help.
![screen shot 2015-03-09 at 4 41 38 pm](https://cloud.githubusercontent.com/assets/158591/6563934/56d0704a-c67b-11e4-8ec1-11b60b740f95.png)

**Comment by zachhowe** [comment]
Add A16FF353-8441-459E-A50C-B071F53F51B7 to DVTPlugInCompatibilityUUIDs of Alcatraz.xcplugin/Contents/Info.plist

**Comment by Pearapps** [comment]
Same

**Comment by wxn0000** [comment]
Same for me. I also tried to build from the master repo, still not showing up in the Window menu.

**Comment by ronbarr** [comment]
Adding row UUID to the plist solved the problem for me.

**Comment by wxn0000** [comment]
Could you please be a little more specific? I just started using Xcode/Alcatraz. Many thanks!



—Xiaoning

**Comment by ronbarr** [comment]
Sure - I took Zach Howe's advice above. Step by step:
- Find the plugin in ~Library/Application Support/Developer/Shared/Xcode/Plugins
- Open the contents of the plugin
- Open the Info.plist in Xcode
- Expand the DVTPlugInCompatibilityUUIDs array
- Create a new entry and paste in A16FF353-8441-459E-A50C-B071F53F51B7C

**Comment by powerje** [comment]
@ronbarr's instructions work but there is an extraneous C in the UUID, i.e.:
```
A16FF353-8441-459E-A50C-B071F53F51B7
```

**Comment by inzan** [comment]
Thank you powerje - I owe you a beer!

**Comment by wxn0000** [comment]
@ronbarr @powerje Thank you guys!!

**Comment by wyd2004** [comment]
@zachhowe It's working! Thank you!

**Comment by RishatShamsutdinov** [comment]
@powerje it's not working after restarting Xcode.

**Comment by Urkman** [comment]
Would be great to have a new release...

**Comment by jurre** [comment]
Yes, I'll try to get to it tonight :)

**Comment by palcalde** [comment]
It doesn't work for me. I double tested that I am openning the correct Xcode 6.2 version, I doubled the checked the UUID of my Xcode app in contents and it is correct. I pasted it into the info plist of Alcatraz and everything, but it doesn't appear in Window tab.

Any solutions? 

Thanks!

**Comment by palcalde** [comment]
Ok I found it. I was openning Library/Application Support/Alcatraz instead of Library/Application Support/Developer/Shared/Xcode/Plugins.

The instructions given by @ronbarr work perfectly fine.

**Comment by wmora** [comment]
@ronbarr's instructions worked for me, with @powerje's UUID correction. Thanks!

**Comment by estebanrules** [comment]
Yep, this fixed it for me.  Thank you!

**Comment by marcoscurvello** [comment]
Worked for me ;)

**Comment by mokagio** [comment]
+1, thanks @ronbarr and @powerje

**Comment by anclefeudor** [comment]
Shit, most of plugins just stop to work after this update!

**Comment by huynguyen** [comment]
@anclefeudor A lot of them haven't updated their own Info.plist, you can add the UUID to the respective plugins the same way.

**Comment by ArtSabintsev** [comment]
Back in business! Thank you @zachhowe and @ronbarr!

**Comment by wsof401** [comment]
@ronbarr  Adding 'A16FF353-8441-459E-A50C-B071F53F51B7' row into DVTPlugInCompatibilityUUIDs arrays doesn't work for me

**Comment by Fogh** [comment]
Adding `A16FF353-8441-459E-A50C-B071F53F51B7` into DVTPlugInCompatibilityUUIDs works with Xcode 6.2

**Comment by p0fi** [comment]
Adding 'A16FF353-8441-459E-A50C-B071F53F51B7' row into DVTPlugInCompatibilityUUIDs arrays doesn't work for me

**Comment by revolter** [comment]
> Create a new entry and paste in A16FF353-8441-459E-A50C-B071F53F51B7C

or `A16FF353-8441-459E-A50C-B071F53F51B7`?

**Comment by wxn0000** [comment]
No "C"



—Xiaoning

**Comment by revolter** [comment]
@wxn0000, It worked, thanks! It would be great if @ronbarr could edit his comment.

**Comment by wxn0000** [comment]
If you read the next comment, which explicitly pointed out that there was a typo.



—Xiaoning

**Comment by pronebird** [comment]
Yeah wtf, there is no C in UUID. Why is it broken though on each release?

**Comment by revolter** [comment]
@wxn0000, I saw, but I was in a hurry and I didn't read it _(because, as we all know, [users don't read anything][1])_. And for others like me _(or not)_ it's way way way better to edit that typo instead of pointing it out in another reply. What if the reply __wasn't__ immediately following the one with the typo?

  [1]: http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html

**Comment by jurre** [comment]
I've updated the comment

**Comment by brycezhang** [comment]
@ronbarr, thanks, it's work!
