### ISSUE TITLE
Plugin Screnshots go upside down

### ISSUE THREAD

**Issue by dev4dev** [alcatraz/Alcatraz#227]
after clicking on screenshot it flips like this. OSX 10.9.5/Xcode 6.2
![screen shot 2015-03-11 at 21 20 21](https://cloud.githubusercontent.com/assets/722407/6604880/710ba74e-c834-11e4-8ea0-f38a9ea5d800.png)

**Comment by supermarin** [comment]
@kattrali shucks... totally forgot about that bug on 10.9.

**Comment by kattrali** [comment]
Argh! I forgot too.

**Comment by kattrali** [comment]
Argh! I forgot too. And I use 10.9 and 10.10 still!

**Comment by ZaneH** [comment]
10.11:
<center><img src="http://i.imgur.com/Y74YPqb.png"/></center>

**Comment by supermarin** [comment]
@ZaneH  Haha, IDK what to say: OSX 10.11, Xcode 7.1.1:
<img width="945" alt="screen shot 2015-11-16 at 9 26 51 pm" src="https://cloud.githubusercontent.com/assets/627285/11203429/cddcce9c-8ca8-11e5-8cbf-96d621d7ad47.png">

**Comment by ZaneH** [comment]
To be honest, I thought it was pretty humorous when I saw it. I refreshed the list and it seemed to fix the images.

**Comment by dev4dev** [comment]
yep, this happens sometime, but who cares

**Comment by nguyenvietson** [comment]
443

**Comment by nguyenvietson** [comment]
#443
