### ISSUE TITLE
How should Alcatraz handle plugins in the skipped bundles list

### ISSUE THREAD

**Issue by Ashton-W** [alcatraz/Alcatraz#283]
See #281 #282

The above issue is about resolving Alcatraz itself being in the skipped bundles list. How should we handle Alcatraz installed plugins being in the skipped bundles list?

We could include a script to remove the plugin's entry upon install, giving similar behaviour to the proposed solution for Alcatraz itself.

Alcatraz should probably be aware of which installed plugins are being prevented from loading, so in the plugins list UI we can inform the user and give instructions to fix it ("Fix issues").

**Comment by guillaume-algis** [comment]
My opinion is that such plugins should appear in the list, but with a different button state. Something like this:

![capture d ecran 2015-05-31 a 16 55 20](https://cloud.githubusercontent.com/assets/1041337/7902349/65511fa2-07b7-11e5-8920-e82af3f9f40d.png)

Clicking the "Blocked" button would remove the plugin from the skipped list, restoring it to the installed state.

---------------

On a side note, I think plugins not yet supported in the user's Xcode version (ie. plugins not having the right Xcode UUID in their Info.plist) should behave similarly

![capture d ecran 2015-05-31 a 16 59 04](https://cloud.githubusercontent.com/assets/1041337/7902367/cf23f2ec-07b7-11e5-9432-dff2e7c4ab91.png)

Clicking on the button then does nothing (or maybe explain what is going on), and *maybe* alt-clicking force-installs the plugin by modifying the Info.plist with the current Xcode UUID.

This would (hopefully) prevent the rise of opened issues for each Xcode release, and the use of dirty hacks like the `find | xargs | plutil` script to add the Xcode UUID to all plugins.

**Comment by jurre** [comment]
Yes, I agree with @guillaume-algis, thanks for the detailed writeup!

**Comment by guillaume-algis** [comment]
FYI, I started implementing this on https://github.com/guillaume-algis/Alcatraz/tree/feature/xcode-blacklist

**Comment by arturgrigor** [comment]
I've implemented this script to automatically mark all the installed plugins as compatible with a version of Xcode: https://github.com/arturgrigor/ForceLoadXcodePlugins
