### ISSUE TITLE
Alacatraz's window can be resized to ridiculous sizes

### ISSUE THREAD

**Issue by guillaume-algis** [alcatraz/Alcatraz#321]
It's currently possible to resize Alcatraz to ressemble something like this:
![capture d ecran 2015-07-08 a 17 13 17](https://cloud.githubusercontent.com/assets/1041337/8574029/d9e38512-2594-11e5-90dd-ebd188e6fb19.png)

or this:
![capture d ecran 2015-07-08 a 17 13 32](https://cloud.githubusercontent.com/assets/1041337/8574034/dec0182a-2594-11e5-9a12-16e9798c6f29.png)

The small size is more problematic as it's unusable in this state. Overall, this is still a minor issue :)

**Comment by supermarin** [comment]
:+1: I guess the easiest option is to disable resizing.
If we enable auto-layout for it, it might mess the images (we might need to re-render)

**Comment by guillaume-algis** [comment]
:+1: great, thanks kattrali!
