### ISSUE TITLE
The tool don't work normally .

### ISSUE THREAD

**Issue by wlkfec** [alcatraz/Alcatraz#338]
I have installed Alcatraz by the command line , but when I running the Xcode application , the tool has a mistake .
![problem](https://cloud.githubusercontent.com/assets/6466299/9298255/29c3fb1c-44de-11e5-90c6-353b1d1f6b95.jpg)
then I check my system , the command line tool is also installed successfully .

**Comment by Matthewspear** [comment]
[This article helped me out](http://pablin.org/2015/05/27/re-enable-alcatraz-on-xcode-6-dot-3-2-or-newer/), basically Xcode only gives you one chance to load code bundles and if you miss it you need to reset a specific default.

The command is: ```defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2```
 
Be sure to replace your version number of xcode at the end of the line and that Xcode is not open when you execute the code from within the terminal.
