### ISSUE TITLE
Package Manager window missing segmented controls

### ISSUE THREAD

**Issue by alexcruice** [alcatraz/Alcatraz#348]
**Symptom:** The main Alcatraz window is missing the set of controls usually found just under the search bar (where it usually has: All, Installed, Plugins, Color Themes and Templates).

I have tried uninstalling and reinstalling Alcatraz, the symptom persists.

<img width="273" alt="screen_shot_2015-09-14_at_10_11_14_pm" src="https://cloud.githubusercontent.com/assets/3786095/9849456/947c13f2-5b2e-11e5-9c46-39eba5b7fe1b.png">

**Running:** Mac OS X 10.9.5 (13F1112), Xcode 6.2 (6C131e)

Found the following messages in Console:
```
14/09/2015 10:22:13.625 pm	Xcode[86413]	Unknown segmented cell style 8 in endCapWidthForStyleAndSize
14/09/2015 10:22:13.625 pm	Xcode[86413]	Unknown segmented cell style 8 in bezelInsetsForStyleAndSize
14/09/2015 10:22:13.625 pm	Xcode[86413]	Unknown segmented cell style 8 in cuiPixelHeightForStyleAndSize
14/09/2015 10:22:13.626 pm	Xcode[86413]	Unknown segmented cell style 8 in bezelInsetsForStyleAndSize
14/09/2015 10:22:13.626 pm	Xcode[86413]	Unknown segmented cell style 8 in cuiPixelHeightForStyleAndSize
14/09/2015 10:22:13.626 pm	Xcode[86413]	Unknown segmented cell style 8 in preferredHeightForStyleAndSize
14/09/2015 10:22:13.626 pm	Xcode[86413]	Unknown segmented cell style 8 in endCapWidthForStyleAndSize
14/09/2015 10:22:13.626 pm	Xcode[86413]	Unknown segmented cell style 8 in bezelInsetsForStyleAndSize
14/09/2015 10:22:13.626 pm	Xcode[86413]	Unknown segmented cell style 8 in cuiPixelHeightForStyleAndSize
14/09/2015 10:22:13.627 pm	Xcode[86413]	Unknown segmented cell style 8 in bezelInsetsForStyleAndSize
14/09/2015 10:22:13.627 pm	Xcode[86413]	Unknown segmented cell style 8 in cuiPixelHeightForStyleAndSize
14/09/2015 10:22:13.627 pm	Xcode[86413]	Unknown segmented cell style 8 in bezelInsetsForStyleAndSize
14/09/2015 10:22:13.627 pm	Xcode[86413]	Unknown segmented cell style 8 in cuiPixelHeightForStyleAndSize
14/09/2015 10:22:13.627 pm	Xcode[86413]	Unknown segmented cell style 8 in preferredHeightForStyleAndSize
14/09/2015 10:22:13.628 pm	Xcode[86413]	Unable to simultaneously satisfy constraints:
(
    "<NSLayoutConstraint:0x7fc63da266b0 H:[NSPopUpButton:0x7fc63da21fe0(30)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fc640dddac0 h=--& v=&-- H:[NSPopUpButton:0x7fc63da21fe0(35)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fc63da266b0 H:[NSPopUpButton:0x7fc63da21fe0(30)]>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
```

**Comment by guillaume-algis** [comment]
Hu. I __may__ have messed up something in #313.
To be honest I had no install of 10.9 handy (and still don't) so I didn't test the change on it :/.

**Comment by jmotohisa** [comment]
I have the same problem under the same environment. I found following warnings at ATZPluginWindowControler.xib. in the Xcode project.

    file:///somewhere/Alcatraz/ATZPluginWindowController.xib: warning: Attribute Unavailable: Separated Segment  Style on OS X versions prior to 10.10
    /somewhere/Alcatraz/Alcatraz/ATZPluginWindowController.xib Frame for "Plugins, Color Themes, Templates" will be different at run time.
    /somewhere/Alcatraz/Alcatraz/ATZPluginWindowController.xib Vertical position will be 16 at run time but is 4 in the canvas.
    /somewhere/Alcatraz/Alcatraz/ATZPluginWindowController.xib Width will be 258 at run time but is 259 in the canvas.
    file:///Users/motohisa/working/Alcatraz/Alcatraz/ATZPluginWindowController.xib: notice: Clipped Content: View is clipping its content
    /somewhere/Alcatraz/Alcatraz/ATZPluginWindowController.xib Frame for "All, Installed" will be different at run time.
    /somewhere/Alcatraz/Alcatraz/ATZPluginWindowController.xib Vertical position will be 16 at run time but is 4 in the canvas.

**Comment by jmotohisa** [comment]
I found a solution. If I change the style of segmented controls from "separated" to "rounded" by editing ATZPluginWindowController.xib, the segmented controls appear. It builds and works nicely under Xcode 6.2, but if the style is "separated", the segmented controls disappear from the interface builder window. I have not tested with upper version of Xcode.

**Comment by guillaume-algis** [comment]
This brings the question of Alcatraz support of older Xcode and OS X versions.

Given Apple only focus on the last version of Xcode I'd be tempted to do the same, and only provide support for the latest Xcode major version. This would mean only supporting Xcode 7.0+ [and OS X 10.10.4+](https://stackoverflow.com/questions/30798329/xcode-7-run-on-mac-osx-10-10-yosemite) as of today.

@supermarin @kattrali @jurre what are your opinions on this?

**Comment by supermarin** [comment]
In general, we support the current major and previous major version of OSX and current major version of Xcode (as there's no reason one shouldn't update Xcode).

**Comment by kattrali** [comment]
Agreed, it's hard to support what we aren't using/have available, and I keep latest Xcode almost always.

**Comment by jurre** [comment]
Yeah, I agree with that as well

**Comment by guillaume-algis** [comment]
Ok great, I'll update the README and website.

Closing this as we don't support Xcode 6 and OS X 10.9 anymore.
If you absolutely need to use Alcatraz with this configuration though, jmotohisa's solution to this issue should work:
> change the style of segmented controls from "separated" to "rounded" by editing ATZPluginWindowController.xib
