### ISSUE TITLE
Feature: Alcatraz should appear in dock tile menu 

### ISSUE THREAD

**Issue by dwicke01** [alcatraz/Alcatraz#349]
I think it would make sense to appear in the dock menu in the same way as any other open window. I wrote it up on my fork but when I was about to make a pull request I noticed that I forgot to look at the guidelines for contributing, and that I should raise an issue before adding a feature. Also I am yet to write tests, I'm working on that now. Here is my fork: https://github.com/dwicke01/Alcatraz/tree/DockTileMenuOption

**Comment by iiiyu** [comment]
I have same problem on Xcode Version 7.1 (7B91b).

**Comment by supermarin** [comment]
@dwicke01 thanks for the suggestion!

We're considering making Alcatraz an .app which would solve this.
I don't think swizzling is the way to go :)
