### ISSUE TITLE
failed install plugins with Alcatraz and Xcode 7.

### ISSUE THREAD

**Issue by zinwalin** [alcatraz/Alcatraz#353]
when install plugins in Alcatraz, the progress bar restores to 0 as soon as clicking the install button..
how to fix it?

Alcatraz 1.1.8 and Xcode 7 release.

**Comment by jurre** [comment]
Most likely is that the plugin maintainer hasn't updated their plugin to work with the latest xcode

**Comment by rostired** [comment]
Go to  ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ and remove all plug-ins in it . And  
reinstall Alcatraz

**Comment by lonkly** [comment]
@rostired it does not help

**Comment by j4nos** [comment]
got this error in Xcode 7:

2015-10-02 16:53:26.518 Xcode[1312:11323]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/extjanos/Library/Developer/Xcode/DeveloperPortal%207.0.1.db).
2015-10-02 16:53:41.701 Xcode[1312:11614]  IDEIndexDatabase: sqlite3_step failed (19|8: UNIQUE constraint failed: unit.file, unit.target)
... INSERT INTO unit (file,target,provider,pchFile) VALUES (?,?,?,?)
2015-10-02 16:53:41.702 Xcode[1312:11323]  IDEIndexing: Index database reported error, workspace 'Alcatraz'
Error Domain=NSCocoaErrorDomain Code=256 "sqlite3_step failed (19|8: UNIQUE constraint failed: unit.file, unit.target)" UserInfo=0x60000566b500 {NSURL=file:///Users/extjanos/Library/Developer/Xcode/DerivedData/Alcatraz-eyxsyeswyalybqgxownblmvsoeya/Index/Debug/macosx10.11-x86_64/Alcatraz.xcindex/db.xcindexdb, NSLocalizedDescription=sqlite3_step failed (19|8: UNIQUE constraint failed: unit.file, unit.target), NSLocalizedFailureReason=INSERT INTO unit (file,target,provider,pchFile) VALUES (?,?,?,?)}

**Comment by githotto** [comment]
Had the first message "...Using pre-existing ... 207.0.1.db" in both Xcode7.01 and Xcode7.1beta2.
The last messages (from "...sqlite3..." and onwards) I only see in Xcode7.1beta2 !?
Still I'm not seeing (in either Xcode7.01 or Xcode7.1beta2) the Xcode>Window>PackageManager menu-item? Anybody suggestions how to get this back with probably some Terminal.app related command sequences?

**Comment by nyotis** [comment]
can someone take care of the Xcode 7.0.1 compatibility please?

**Comment by jurre** [comment]
> can someone take care of the Xcode 7.0.1 compatibility please?

I'd be happy to see your pull request :)

**Comment by nyotis** [comment]
On its way!Nik Yotis---- On Tue, 13 Oct 2015 11:43:19 +0200  Jurre<notifications@github.com> wrote ----can someone take care of the Xcode 7.0.1 compatibility please?I'd be happy to see your pull request :)—Reply to this email directly or view it on GitHub.

**Comment by nyotis** [comment]
@jurre well, building the Clang-Format source works fine for now

**Comment by jurre** [comment]
Great :)
