### ISSUE TITLE
Can Alcatraz work when Xcode7.01 and Xcode7.1beta2 are installed on the same machine?

### ISSUE THREAD

**Issue by githotto** [alcatraz/Alcatraz#358]
Previously Alcatraz worked when I only had Xcode7.01 installed.
Since I got a lot of Xcode7 playground issues and installed Xcode7.1beta2 most of my problems have gone away. For some previous projects I still need Xcode7.01 and when the official Xcode7.1 GM is available I can get rid of the two versions I currently have.
In order to install the Alcatraz-plugin I either run the command-line install or build the latest Alcatraz project using Xcode7.01/7.1beta2. Unfortunately I don't see the Xcode>Window>PackageManager item.
When building and running the latest Alcatraz project-code in the Xcode7.01/7.1beta2-IDE I'll see in the debugger-console the following message:

2015-10-09 12:34:04.119 Xcode[2163:456896]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/otto/Library/Developer/Xcode/DeveloperPortal%207.0.1.db).

Anybody clues on how to solve this or get at least in one of the two installed Xcode7 versions my PackageManager menu-item back?

**Comment by kevinKyZheng** [comment]
I have the same problem.I solve it by the issue--Not Working On Xcode 7.As @diogoguimaraes said.
1. uninstall the Alcatraz.
2. 
`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0`
`sudo xcode-select --reset`
3.reinstall the Alcatraz.
I use the command line by terminal both install and uninstall.Finally,my both Xcode have Alcatraz.

**Comment by castus** [comment]
@kevinKyZheng works for me too, thanks!

**Comment by OscarSwanros** [comment]
@kevinKyZheng Worked for me too! :+1:

**Comment by johnwatsondev** [comment]
@kevinKyZheng Thanks vm.
I just updated my Xcode from 7.0.1 to 7.1 via dmg file. The `Package Manager` menu is missed.
I followed your approach and just modofied a little bit.
`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1`
Everything is fine.

**Comment by menjiefu** [comment]
@johnwatsondev Thanks!Save my life.

**Comment by johnpatrickmorgan** [comment]
FYI, use `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1` for latest version 7.1.1.

**Comment by Jules2010** [comment]
I had to update mine to 7.2 for the current beta, but I don't now have alcatraz for the release version 7.1.1, if I uninstall and repeat the sets above won't this remove it for 7.2 ?

My question is can I run Alactraz on beta a release versions at the same time? if so how ?

**Comment by guillaume-algis** [comment]
Closing as the `DVTPlugInManagerNonApplePlugIns` issue was fixed in #315.

@Jules2010 Yes you can run Alcatraz on multiple versions of Xcode. You don't have anything special to do, plugins are shared between different Xcode versions.
