### ISSUE TITLE
alcatraz does not show in the menu at xcode 7.1 

### ISSUE THREAD

**Issue by yishuiliunian** [alcatraz/Alcatraz#365]
alcatraz does not show in the menu at xcode 7.1

**Comment by Gladkov-Art** [comment]
I've got the same problem. Tried to reinstall Alcatraz as often do after updating Xcode.

**Comment by alexmorral** [comment]
Take a look at https://github.com/supermarin/Alcatraz/issues/362#issuecomment-150457101

**Comment by Gladkov-Art** [comment]
thanks!

**Comment by alonecuzzo** [comment]
Doesn't work.

**Comment by jpincheira** [comment]
Did all of the suggestions, and won't work as well. :cry:

**Comment by StuartWebster** [comment]
@jpincheira's method got Alcatraz working for me again. Thanks!

**Comment by rakaramos** [comment]
@jpincheira you saved my day! thanks!

**Comment by EvanLu** [comment]
I tried @jpincheira method and then deleted previous defaults, it works!

defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1

**Comment by jaderYang** [comment]
@jpincheira U saved my night! thanks!

**Comment by DanielAsher** [comment]
@EvanLu 
I found the deleting of previous defaults step is required.

thanks!

**Comment by aotian16** [comment]
Thanks to all!

**Comment by manymingge** [comment]
@EvanLu tks a lot!

**Comment by KetilDeng** [comment]
I try  @jpincheira method and then try @EvanLu method,but terminal give me message：

Domain (com.apple.dt.Xcode) not found.
Defaults have not been changed.

**Comment by jsuo** [comment]
@jpincheira Thanks. It's work!

**Comment by LawrenceZhang** [comment]
type "defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1" in terminal  will fix this issue, restart Xcode and load bundles

**Comment by jpincheira** [comment]
@all no problem guys, glad it helped! :+1:

**Comment by onmyway133** [comment]
@jpincheira thanks, it works

```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1
curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh
```

**Comment by santiacho** [comment]
Thanks! @jpincheira and @EvanLu. 

`cd ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins
wget https://github.com/supermarin/Alcatraz/releases/download/1.1.10/Alcatraz.tar.gz --no-check-certificate
tar xzvf Alcatraz.tar.gz
rm Alcatraz.tar.gz
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1`

Restart Xcode and Loada Bundles again.

**Comment by cuiwang** [comment]
@jpincheira you saved my day!

**Comment by xcuYao** [comment]
thanks everybody

**Comment by kevinlee85** [comment]
@KetilDeng Yes, I have the same issue.
I tried defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1
And terminal response:
Domain (com.apple.dt.Xcode) not found.
Defaults have not been changed.

**Comment by rafalwojcik** [comment]
@kevinlee85 Work for me, make sure that 7.1.1 version from command line equal to your Xcode version.

**Comment by jchnxu** [comment]
If you couldn't find DVTPlugInManagerNonApplePlugIns, try look at this http://stackoverflow.com/questions/30361228/why-are-my-xcode-plugins-such-as-clang-format-installed-with-alcatraz-no-longe
