### ISSUE TITLE
Cannot Install Plugins, Installing Button 25% Green, then Fails

### ISSUE THREAD

**Issue by cerniuk** [alcatraz/Alcatraz#367]
Installing plugins fails for all plugins. 

This has been consistent since Xcode 6.3.  Install button changes to "Installing" and the "bar graph" shading on the button progresses to roughly 25 or 30% to the right. Then it rapidly moves back to the left and the button turns back to "Install". Using Xcode Version 7.0 (7A218)

This seems to be a problem that has been around a while.  Lots of posts on the web, no workarounds short of using Alcatraz as a catalog and then doing code download and builds on the plugins to install them.

**Comment by jurre** [comment]
This most likely has to do with plugins that haven't added support for a new version of xcode yet. Could you check the logs for any error messages?

**Comment by vulgur** [comment]
Same issue on Xcode Version 7.1 (7B91b). How can I check the logs?

**Comment by cerniuk** [comment]
Lots of junk spews from Xcode in logs but this is all there is for Alcatraz :

11/5/15 5:44:16.469 PM Xcode[10651]: Updating Repo: /Users/me/Library/Application Support/Alcatraz/Plug-ins/Alcatraz
11/5/15 7:56:52.798 PM Xcode[10651]: Updating Repo: /Users/me/Library/Application Support/Alcatraz/Plug-ins/AutoHighlightSymbol
11/5/15 7:56:53.733 PM Xcode[10651]: Cloning Repo: /Users/me/Library/Application Support/Alcatraz/Plug-ins/ACCodeSnippetRepository
11/5/15 7:56:54.105 PM Xcode[10651]: Git Clone output: Cloning into '/Users/me/Library/Application Support/Alcatraz/Plug-ins/ACCodeSnippetRepository'...

Every "Install" button does this, no exception.  I made it down to "Jumper" clicking every Install one after the other.

Those plugins I have installed by compiling the source show up under Alcatraz where the button offers a remove that works.

**Comment by cerniuk** [comment]
I tried removing the plugins that offered remove.  They removed. From Alcatraz, they won't install again.  I can compile them to install them, no problem.

**Comment by supermarin** [comment]
@cerniuk we'll need more logs, this is not where it fails.

`tail -f /var/log/system.log`

**Comment by MiguelChiang** [comment]
same here, manual build the plugin and install is ok. xcode 7.1

@supermarin logs as below after click the install button. Thanks mate.

> Cloning Repo: /Users/mic/Library/Application Support/Alcatraz/Plug-ins/CComment
> Git Clone output: Cloning into '/Users/mic/Library/Application Support/Alcatraz/Plug-ins/CComment'...
> Xcodebuild output: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by vulgur** [comment]
Problem solved. Something is wrong with my xcodebuild, after I updated Xcode to 7.1.1 and re-agreed the xcodebuild-license, somehow it does work again.

**Comment by supermarin** [comment]
@MiguelChiang lease search the issues, this has been reported many times.

`sudo xcode-select -s /Applications/Xcode.app` should fix it if you've updated to the newest Xcode.
