### ISSUE TITLE
Install some plugins by Alcatraz and then restart Xcode, Alcatraz disappears in the Xcode menu

### ISSUE THREAD

**Issue by wonderffee** [alcatraz/Alcatraz#375]
At the beginning, Alcatraz does not work in my new Xcode 7.1. I uninstall Alcatraz and reinstall it,  restart Xcode, it does show in my Xcode menu. Then I install some plugins by Alcatraz and restart Xcode, these plugins work well, but Alcatraz disappears in the Xcode menu. Just so weird...

Try uninstall and reinstall it for many times, only wasting time.

Does someone has the same problem?

**Comment by Alchemistxxd** [comment]
I have the same problem and my Alcatraz has never appeared in Xcode7.1. I have tried some solution, and all doesn't work.

**Comment by dwicke01** [comment]
I'm also having the same problem

**Comment by qx** [comment]
+1

**Comment by qx** [comment]
![2015-11-08 18 56 14](https://cloud.githubusercontent.com/assets/648406/11019964/785822fa-864a-11e5-94d3-1f38b9f35797.png)
![2015-11-08 18 55 25](https://cloud.githubusercontent.com/assets/648406/11019965/7883441c-864a-11e5-83bf-bae0aecc4d6c.png)

**Comment by zhangjf108** [comment]
+1

**Comment by teki** [comment]
+1

**Comment by tskulbru** [comment]
Have the same problem using Xcode 7.1. It looks like it fails when displaing the `Load Bundles` dialog at xcode startup

**Comment by CallumHoward** [comment]
same here, upgraded to 7.1.1 and now there is no option in the menu as above

**Comment by hefgi** [comment]
Same problem here on Xcode 7.1 !

**Comment by fewtime** [comment]
+1

**Comment by supermarin** [comment]
Duplicate, please search github issues!

**Comment by wonderffee** [comment]
@Alchemistxxd 
Just check path "~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/", Alcatraz.xcplugin is gone, maybe it's the core problem. Reinstall Alcatraz solves it.
Still have no idea why Alcatraz.xcplugin is auto gone

**Comment by Alchemistxxd** [comment]
@wonderffee  just build and install the newest commit, the bug is fixed. :)
