### ISSUE TITLE
it's not work in Xcode 7.1

### ISSUE THREAD

**Issue by irobbin1024** [alcatraz/Alcatraz#377]
i install Alcatraz with command `curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh`

and install success.

i open my Xcode and choose load bundle,but i can't found alcatraz in window menu.

so i try to fix issues, try execute command 

```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
```

this command was work perfect before Xcode version. but 7.1 doesn't work for me.

help! thank you 🙏

**Comment by irobbin1024** [comment]
should i install with build source code ?

no, it's doesn't work too.

**Comment by donly** [comment]
I have the same problem, and my Xcode version is **7.1.1**

**Comment by y284663247** [comment]
me to ,version 7.1.1

**Comment by ben181231** [comment]
Me too. Version 7.1.1 on El Capitan.

**Comment by iosliujun** [comment]
me to ,version 7.1.1

**Comment by supermarin** [comment]
please search issues.

**Comment by donly** [comment]
I follow the #378 , it work fine after I restart Xcode twice, amazing!
