### ISSUE TITLE
XCode7.1 Alcatraz isn't show in menu Window

### ISSUE THREAD

**Issue by jackyzonewen** [alcatraz/Alcatraz#378]
i have do some step as follow:
1. reinstall Alcatraz

2. find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

3. defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1

4. restart XCode, And Select Load bundles

All Other PlugIns is Work fine, Only Alcatraz 's menu Package Manager in Window not show, 
My OS is 10.10.5, XCode 7.1, xcode-select -v 2339

**Comment by jackyzonewen** [comment]
i update my XCode7.1 to 7.1.1,then i do this step once again, i work fine，amazing

**Comment by jackyzonewen** [comment]
i update my XCode7.1 to 7.1.1,then i do this step once again, i work fine，amazing

**Comment by iosliujun** [comment]
i have do all steps in xCode7.1.1 ,after i select Load bundles , my Xcode can not do anything but only exit,and Package Manager also not show...

**Comment by luna-moonfang** [comment]
@iosliujun +1
