### ISSUE TITLE
Alcatraz install miss package Manage menu in two version xcode

### ISSUE THREAD

**Issue by qx** [alcatraz/Alcatraz#380]
I have 2 versions xcode 6.4/7.1 ,after installing mentioned, 6.4 worked,but 7.1 have nothing on menu.

**Comment by Shawkaine** [comment]
I put the UUID of 7.1 on the plist, it didn't work either, still no see pack manager

**Comment by Shawkaine** [comment]
type  defaults delete com.Apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1
in terminal , then the load/skip bundle waring showed again, select load, pack manager showed up

**Comment by josephsieh** [comment]
I have Xcode 7.1.1 and Xcode 6.4 installed on OS X 10.11.1.  I tried Shawkaine's suggestion, the package manager is still no-show.

**Comment by bradjasper** [comment]
Was able to get my bundles reloaded with this command:

    defaults delete com.Apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1

Then re-approve all bundles. I don't see the menu item, however.

**Comment by esttorhe** [comment]
Did what @bradjasper suggested; same result.

Now I do have all the other plug-ins but `Alcatraz` is not showing however

Even added the `UUID` to it and still no dice :/

**Comment by Shawkaine** [comment]
1.  Add your current Xcode's UUID to the plugin‘s info plist
- defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID   to get the UUID
- find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -Alcatraz Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add  yourCurrentUUID

2. reload the bundle warning as I said above
- defaults delete com.Apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-yourCurrentVersion

**Comment by kattrali** [comment]
This is fixed in release 1.1.13 along with #377, #378, #379, #381, and #383 by #382.
