### ISSUE TITLE
xcode7.1.1

### ISSUE THREAD

**Issue by syyjay** [alcatraz/Alcatraz#381]
xcode 7.1.1 install fail

**Comment by hezt95** [comment]
The same.
Xcode 7.1.1 + OS X 10.11.1

**Comment by syyjay** [comment]
In OSX 10.11.1  the alcatraz will install success in Xcode.7.1.1?

**Comment by jkyin** [comment]
When I have updated Alcatraz to latest version, and then it disappear from Xcode.

Xcode version 7.1.1

**Comment by superwave** [comment]
OSX 10.11.1 + Xcode 7.1.1 (7B1005)
update Xcode to latest version make the package manager appear in the first time, and i never shown.
but plugins I installed before works fine.

I'v tried @hezt95 solution but it doesn't work either.

**Comment by hezt95** [comment]
@supermarin Me too. 

update Xcode to latest version make the package manager appear in the first time, and it never shown again.

**Comment by nickhart** [comment]
Also unable to install on Xcode 7.1.1.  I removed Alcatraz (per uninstall instructions) and ran the "sudo xcode-select --reset" command as well (I have Xcode 6 also on my system).  I re-installed and still no luck.  No "package manager" shown in the "Window" menu.

**Comment by nickhart** [comment]
Rebuilt from master and verified this fixes my issue.  Thanks!

**Comment by supermarin** [comment]
Thanks for letting us know! it's fixed in master, we'll ship an update soon
