### ISSUE TITLE
Xcode 7.1.1 quits unexpectedly when clicking Package Manager

### ISSUE THREAD

**Issue by ImEric** [alcatraz/Alcatraz#384]
Xcode(7.1.1) quits unexpectedly after clicking Package Manager. I tried to build it in Xcode and click the Package Manager at the same time, the following error message showed up:

Application Specific Information:
ProductBuildVersion: 7B1005
UNCAUGHT EXCEPTION (NSInvalidArgumentException): *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
UserInfo: (null)
....

[crash_log.txt](https://github.com/alcatraz/Alcatraz/files/39708/crash_log.txt)

**Comment by kattrali** [comment]
Weird, looks like you were missing the Helvetica Neue font. I'm not sure how that happens on 10.11.
