### ISSUE TITLE
Alcatraz has disappeared after XCode was upgraded up to 7.1.1

### ISSUE THREAD

**Issue by lovesuper** [alcatraz/Alcatraz#385]
Reinstalling and any kinds of clearing have no effect.

**Comment by samuelbeek** [comment]
:+1:

**Comment by jurre** [comment]
Which version of Alcatraz do you have installed?

**Comment by lovesuper** [comment]
Hmm.. After a few reboots of system and dancing with claps it comes to working...

**Comment by samuelbeek** [comment]
I have the newest version of Alcatraz, and Xcode Version 7.1.1 on a brand new machine; It worked after installing and reinstalling it several times. Can't figure out what's causing the problem.

**Comment by jurre** [comment]
It is an issue that should have been fixed in the latest release, let's see if more people run into it or if it was indeed properly fixed.
