### ISSUE TITLE
Can't install since xCode 7.1.1 update 

### ISSUE THREAD

**Issue by Maxatma** [alcatraz/Alcatraz#387]
I were trying to install it / clone+build, doesn't work. Nothing changes. 
Xcode Version 7.1.1 (7B1005)

**Comment by ngothanhtai** [comment]
I have same problem.

**Comment by jurre** [comment]
What version of Alcatraz do you currently have installed?

**Comment by c-mendoza** [comment]
I have the same issue on Xcode 7.0.1 and Alcatraz 1.1.13

**Comment by ngothanhtai** [comment]
I reinstalled and it works. Maybe the first time I ignore this message.
https://gyazo.com/a19db2bbec47c04b0ecf6c34dbeaa168

**Comment by sam-wan** [comment]
I have the same issue.

I have uninstalled Alcatraz (using the instruction on the website) and reinstalled.  No luck

**Comment by hugovanderlei** [comment]
same problem here

**Comment by ForkPanda** [comment]
I have the same problem on Xcode 7.1.1 & Alcatraz 1.1.13

**Comment by w9174760** [comment]
I have the same issue.

**Comment by yuan232007** [comment]
I have the same problem on Xcode 7.1.1 and the Alcatraz new version

**Comment by yyny1789** [comment]
I have same problem.

**Comment by Maxatma** [comment]
uninstall + install helped me today)

**Comment by danishin** [comment]
+1

**Comment by candledragle** [comment]
I have the same problem on Xcode 7.1.1

**Comment by yangtaoNewGame** [comment]
@ngothanhtai , I select load bounds  ...but still can't  install any plugin ..   why ?

**Comment by yangtaoNewGame** [comment]
I updated mac os capitan ,  xcode could installed plugin ...   if anyone like me , you may try it.

**Comment by NSRover** [comment]
What worked for me was completely removing Alcatraz first. Then I cloned the repo and build the project myself from Xcode. 

Next I installed the VVDocumenter plugin and it works fine now.

**Comment by fvvliet** [comment]
same same

**Comment by rizwankce** [comment]
Cloning the Repo and build the project brings back Package Manager option.

**Comment by fvvliet** [comment]
@rizwankce : sorry, it does not.

**Comment by rizwankce** [comment]
@fvvliet I have followed these steps.
- Removed all files related to Alcatraz
- Cloned Repo and build using xCode
- Quit the xCode and reopened.
- Clicked "Load Bundle" when the xCode asked

**Comment by fvvliet** [comment]
@rizwankce : Ok I'll try again, thanks

**Comment by ForkPanda** [comment]
I have already solved the problem.

And I write a shell script to reload all of Xcode plug-ins.

[Portal Here!](https://github.com/ForkPanda/RescueXcodePlug-ins)

It works for me.

**Comment by hugovanderlei** [comment]
Thanks @ForkPanda! it works!

**Comment by yyny1789** [comment]
Thanks @ForkPanda!

**Comment by virenenskully** [comment]
thanks ForkPanda!

**Comment by GarveyCalvin** [comment]
Thank you. @rizwankce 
It works!

**Comment by pitkane** [comment]
Thank you @ForkPanda, works like a charm :)

**Comment by xiaonan0527** [comment]
thank you @ForkPanda

**Comment by guillaume-algis** [comment]
The issue was probably caused by two things:

- Alcatraz being added to the "skipped plugins" list of Xcode, which was fixed in #315
- All plugins not including the new Xcode UUID just after its release, which is still a problem, but progress on this will be tracked in #442 

Closing as this is becoming a "thank you" thread :). Please leave a comment if you feel this issue was not yet fixed and this should be left open. Thanks everyone!
