### ISSUE TITLE
Create a contributors repo?

### ISSUE THREAD

**Issue by orta** [alcatraz/Alcatraz#391]
Hey there, so things are looking good from the perspective of having alcatraz as an org, :ok_hand: - I'd love it if the Alcatraz maintainers can start taking some time to think about ways in which others can start to contribute at a higher level and reduce some of the burden on you.

@ashfurrow and I thought about this for a while on a project that we were running, once we were starting to see almost daily PRs and it was hard to keep on top of. So we created the [Moya contributors guidelines](https://github.com/Moya/contributors), which is basically the promise from the Moya maintainers to people who want to contribute. It documents how we would work with others to dilute our power, and to ensure that a lot of voices and opinions are heard and respected. It has greatly reduced the time we need to put into the project for the two of us, and significantly improved the amount of ownership others feel towards the project. It's been a net win.

Our approach leans pretty far towards extreme openness ( 1 PR and you get push rights ) but a systematic approach like this means that there's less backroom dealing around who should get the ability to merge PRs for example. It's been working out pretty well in the [RxSwiftCommunity org](https://github.com/RxSwiftCommunity) i the last few weeks too.

**Comment by kattrali** [comment]
Thanks @orta. We have a structure in place for managing contributions and some potential places for contributors to start via the intended feature set in #201. I might pop it out into a link in the readme for visibility. In the meantime, we are having discussions about some potential additions to the team.
