### ISSUE TITLE
Installation fails on 7.1.1

### ISSUE THREAD

**Issue by sedlast** [alcatraz/Alcatraz#394]
Hi,
I was using both Xcode & Xcode-beta.
At some point (I guess it happened by installation Xcode-beta) my problems started.
I found a solution to remove everything (plugins, settings, xcode-select reset, ..)

I tried to install Alcatraz from scratch but it failed on 'defaults read' command.

You can see my "workaround" here:
user@mac ~                                                                                                                                                                   [13:19:02]
> $ curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
2015-11-30 13:19:20.576 defaults[45400:412665]
The domain/default pair of (${HOME}/Library/Preferences/com.apple.dt.Xcode, DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1) does not exist

user@mac ~                                                                                                                                                                   [13:19:20]
> $ defaults read -app Xcode DVTPlugInManagerNonApplePlugIns-Xcode-$(xcrun xcodebuild -version | head -n1 | awk '{ print $2 }')
2015-11-30 13:19:31.576 defaults[45435:412750]
The domain/default pair of (${HOME}/Library/Preferences/com.apple.dt.Xcode, DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1) does not exist

user@mac ~                                                                                                                                                                   [13:20:51]
> $ defaults write -app Xcode DVTPlugInManagerNonApplePlugIns-Xcode-$(xcrun xcodebuild -version | head -n1 | awk '{ print $2 }') '{}'

user@mac ~                                                                                                                                                                   [13:21:32]
> $ curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   590    0   590    0     0    799      0 --:--:-- --:--:-- --:--:--   799
  0  105k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0x Alcatraz.xcplugin/
x Alcatraz.xcplugin/Contents/
x Alcatraz.xcplugin/Contents/Info.plist
x Alcatraz.xcplugin/Contents/MacOS/
x Alcatraz.xcplugin/Contents/Resources/
x Alcatraz.xcplugin/Contents/Resources/ATZPackageListTableCellView.nib
x Alcatraz.xcplugin/Contents/Resources/ATZPluginWindowController.nib
x Alcatraz.xcplugin/Contents/Resources/bitbucket_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/
100  105k  100  105k    0     0  46129      0  0:00:02  0:00:02 --:--:-- 73521

x Alcatraz.xcplugin/Contents/Resources/git_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/github_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/link_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings
x Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings
x Alcatraz.xcplugin/Contents/MacOS/Alcatraz
Alcatraz successfully installed!!1!🍻  Please restart your Xcode (7.1.1).

Please update install script to handle missing value.

Thanks,
Stefan

**Comment by guillaume-algis** [comment]
Hi Stefan,

Thanks for the detailed report. This is the same issue as #392.
It will be addressed with PR #393.
