### ISSUE TITLE
Feature Request: Integrate Info DVTPlugInCompatibilityUUID script into Al

### ISSUE THREAD

**Issue by DataZombies** [alcatraz/Alcatraz#395]
It would be great if Al could run this script to "register" the plugin.
```
#bang Xcode’s UUID into all plugins
XCODEUUID=`defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`

for f in ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/*; do defaults write "$f/Contents/Info" DVTPlugInCompatibilityUUIDs -array-add $XCODEUUID; done
```

**Comment by guillaume-algis** [comment]
Hi Daniel,

This issue has already be discussed extensively in the past (see #122 for example), and the conclusion is that keeping the plugin up to date with Xcode's UUID is the plugin's maintainer's job, not Alcatraz's,. Updating all plugins blindly like that would be bad for the overall Xcode stability.

However, displaying which plugins are out of date and won't work with your currently installed version of Xcode is definitely on the roadmap (#201).
