### ISSUE TITLE
Xcode 7.2 do not run plugins.

### ISSUE THREAD

**Issue by DimonDeveloper** [alcatraz/Alcatraz#400]
I have installed 1.1.15 version, reinstall all plugins, and click load bundles but still it did not help.
Mac OS X 10.11.2.

**Comment by jurre** [comment]
Are you sure the plugins have added support for 7.2 yet?

**Comment by DimonDeveloper** [comment]
You are right, is not one of them does not support Xcode 7.2.

**Comment by jurre** [comment]
It usually takes a few days, you could help by sending pull requests to the plugins, like this: https://github.com/alcatraz/Alcatraz/pull/399
