### ISSUE TITLE
can't install on OS X 10.11.2 and Xcode 7.2

### ISSUE THREAD

**Issue by tianxiewuhua** [alcatraz/Alcatraz#403]
i try command 'curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh'
and failed with error 'mktemp: too few X's in template ‘com.mneorr.Alcatraz’'

**Comment by thor-the-norseman** [comment]
Can verify this on my system as well.

**Comment by guillaume-algis** [comment]
Hmm interesting, I have no issue with `mktemp -t foobar` on my system.

- Which system are you running ?
- Could you please paste the output of `mktemp --version` and `type -a mktemp` here ?

Thanks!

**Comment by thor-the-norseman** [comment]
In my case (I'm not the original filer of the bug):

```Thors-MacBook-Pro:~ thor$ mktemp --version
mktemp (GNU coreutils) 8.24
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Eric Blake.```

```Thors-MacBook-Pro:~ thor$ type -a mktemp
mktemp is /usr/local/opt/coreutils/libexec/gnubin/mktemp
mktemp is /usr/bin/mktemp
mktemp is /usr/local/opt/coreutils/libexec/gnubin/mktemp```

If you're wondering about the 'opt' paths, having Homebrew installed may have something to do with the problem, since that would mean that the GNU version of the tool is being used, as opposed to the built-in OS X one (which doesn't even accept a --version switch).

**Comment by guillaume-algis** [comment]
Yep, that's what I was suspecting :/

Fixed in PR #404.

**Comment by tianxiewuhua** [comment]
this is out put of ```mktemp --version```
```
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Eric Blake.
```
and ```type -a mktemp```
```
mktemp is /usr/local/opt/coreutils/libexec/gnubin/mktemp
mktemp is /usr/bin/mktemp
mktemp is /usr/bin/mktemp
```

**Comment by guillaume-algis** [comment]
Thanks @tianxiewuhua, this is the same problem as thor-the-norseman. You have installed the homebrew package `coreutils`, and force-linked its binaries. The result is that your `mktemp` binary (the GNU version from brew) is shadowing the system's binary (the BSD version, in `/usr/bin/`), hence the error.

See #404 for the full discussion, but there's a good chance this won't be "fixed" in Alcatraz, as the error comes from your particular setup.

**Comment by jurre** [comment]
As @guillaume-algis mentioned, this is not something we want to fix. Please install Alcatraz manually if you cannot use the default OSX utilities, the install script should be pretty straight forward to follow manually, or alternatively you could just clone the repository and build it in Xcode.

**Comment by psophis** [comment]
For anyone that would like a temporary work around for this issue alias mktemp to `/usr/bin/mktemp` prior to running the install script and pipe into your current shell:

```
alias mktemp=/usr/bin/mktemp
curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | zsh
```

**Comment by davidlondono** [comment]
O.o still even if its not your problem you gatta make a solution for the community! or recommend something to do, at least on FAQ or I don't know, but this issue on google just head us to this github issues

**Comment by georgel** [comment]
Alternative fix:

`brew uninstall coreutils
curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh
brew install coreutils`
