### ISSUE TITLE
Xcode 7.2 (7C68) no data.

### ISSUE THREAD

**Issue by z1995r** [alcatraz/Alcatraz#405]
Hi.
When I upgrade Xcode from 7.1 to 7.2, I found that there isn't any data in Alcatraz.
<img width="543" alt="2015-12-18 11 00 56" src="https://cloud.githubusercontent.com/assets/6964772/11888278/a7946ce0-a576-11e5-94ae-db63ee5247ba.png">
And even I tried to uninstall and reinstall Alcatraz(1.1.15) . It's still no data here.

**Comment by jurre** [comment]
Are you maybe behind a proxy or something?

**Comment by z1995r** [comment]
Eh, it works fine before. And my workmates can use it as usual. I am't behind a proxy and we use the same Wi-Fi. I think it is not the problem of network environment, because I found out that there isn't any download task when I open the Alcatraz, is this the problem?
<img width="546" alt="2015-12-22 10 48 15" src="https://cloud.githubusercontent.com/assets/6964772/11946872/4aa2eecc-a89a-11e5-877e-35d382d77464.png">

**Comment by z1995r** [comment]
My Mac OS Version is 10.11.1 (15B42). And I have already restore the network settings to default, not work :( . 
Any other information can I provide?  Thx.

**Comment by z1995r** [comment]
All right ... I have tried download the source code and run . Get serval errors when ATZDownloader instance execute 
/ - (void)downloadFileFromPath:(NSString *)remotePath progress:(ATZDownloadProgress)progress
                                                  completion:(ATZDataDownloadCompletion)completion

2015-12-22 11:29:35.605 Xcode[50314:2551048]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-9542/DVTFoundation/Downloadables/DVTDownloadableIndex.m:73
Details:  Error Domain=NSURLErrorDomain Code=-1001 "Failed to download index with errors: (
    "Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex\" UserInfo={NSUnderlyingError=0x618000c4f4e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"The request timed out.\" UserInfo={NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex}",
    "Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex\" UserInfo={NSUnderlyingError=0x60800045d310 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"The request timed out.\" UserInfo={NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex}"
)" UserInfo={NSLocalizedDescription=Failed to download index with errors: (
    "Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex\" UserInfo={NSUnderlyingError=0x618000c4f4e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"The request timed out.\" UserInfo={NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index-7.2.0-F41BD31E-2683-44B8-AE7F-5F09E919790E.dvtdownloadableindex}",
    "Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex\" UserInfo={NSUnderlyingError=0x60800045d310 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"The request timed out.\" UserInfo={NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, NSErrorFailingURLKey=https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.\n\nOpening: https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex}"
)}
Object:   <DVTDownloadableIndexSourceDocs: 0x608000234200>
Method:   -init
Thread:   <NSThread: 0x610001866280>{number = 31, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

**Comment by z1995r** [comment]
All right .. It seems a bug on OS X 10.11.1 . I will try OS X  10.11.2 later..ˊ_>ˋ

**Comment by z1995r** [comment]
It works fine on OS X 10.11.2 . 
<img width="541" alt="2015-12-28 10 05 21" src="https://cloud.githubusercontent.com/assets/6964772/12020174/1d064526-adb4-11e5-96b4-d119206112b8.png">
