### ISSUE TITLE
https://raw.github.com/alcatraz/alcatraz-packages/master/packages.json has error

### ISSUE THREAD

**Issue by zhuweiDark** [alcatraz/Alcatraz#408]
{
        "name": "SwiftJsonToObj",
        "url": "https://github.com/aotian16/SwiftJsonToObj",
        "description": "json to object plugin",
        "https://github.com/aotian16/SwiftJsonToObj/raw/master/screenshot/SwiftJsonToObj.png"
      },
      {
        "name": "Xmas",
        "url": "https://github.com/onmyway133/Xmas",
        "description": "It's beginning to look a lot like Christmas",
        "screenshot": "https://github.com/onmyway133/Xmas/raw/master/Screenshots/xmas.png"
      },

**Comment by mcfedr** [comment]
Created a pull request to fix this https://github.com/alcatraz/alcatraz-packages/pull/444

**Comment by jurre** [comment]
Thanks!
