### ISSUE TITLE
Alcatraz for xcode beta seems error 

### ISSUE THREAD

**Issue by drduan** [alcatraz/Alcatraz#419]
while i use 
curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh
and terminals works out ` couldn't find an application named "Xcode" defaults unchanged `

**Comment by guillaume-algis** [comment]
Thanks for the report.
This is a harmless error message from `defaults read -app Xcode "$PLIST_PLUGINS_KEY"` part of the script. You're seeing this when installing Alcatraz without having opened Xcode at least once before.
I agree it can be confusing, I'll submit a patch getting rid of this message as soon as I can.

Can you confirm Alcatraz is functioning correctly despite this message?

**Comment by drduan** [comment]
I'm using xcode beta 7.3,
<img width="578" alt="2016-01-29 17 23 21" src="https://cloud.githubusercontent.com/assets/7875572/12671813/13b1e414-c6ad-11e5-990b-f5066c40ff6d.png">

restart and can't find this plugin

**Comment by drduan** [comment]
<img width="588" alt="alcatraz" src="https://cloud.githubusercontent.com/assets/7875572/12671932/de926a8c-c6ad-11e5-8628-787f32391831.png">

**Comment by jurre** [comment]
So is Alcatraz working correctly for you? If yes, we can close this issue :)

**Comment by drduan** [comment]
but no package manager option found  in menu

**Comment by drduan** [comment]
I try to run code with xcode and it shows

**Comment by guillaume-algis** [comment]
The script from alcatraz.io (`https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh`) installs Alcatraz 1.1.15, which predates the inclusion of the Xcode 7.3b UUID (in  `874f4d3`).
So this is normal for the Package Manager option to not appear in Xcode 7.3 if installed that way.

The `defaults unchanged` error is unrelated to this.

**Comment by jurre** [comment]
Thanks @guillaume-algis, I'm going to close this issue then.
