### ISSUE TITLE
Xcode 7.2.1 - no iOS Simulators for running of a project availeble except latest after installing and uninstalling Alcatraz

### ISSUE THREAD

**Issue by userow** [alcatraz/Alcatraz#424]
1) I had fresh version of Xcode 7.2.1 Version 7.2.1 (7C1002)

2) I've installed Alcatraz via 
curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh

3) I opened a project, that I've created earlier - all iOS Simulator's available for running a project, except the latest one, disappeared.

4) I've removed Alcatraz via

rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
rm -rf ~/Library/Application\ Support/Alcatraz/

5) I've restarted Xcode - no iOS Simulators appeared

**Comment by jurre** [comment]
Have you been able to replicate this multiple times and are you sure the only thing you're doing is installing and uninstalling Alcatraz? I'm trying to think of how we could cause this and I'm not sure yet

**Comment by userow** [comment]
Ok, my fault.

Installing Alcatraz just nullifies "Deployment Target" in project properties.

Strange, but now Alcatraz can't install two plugins searched by "realm" keyword.

And crashed Xcode while opening.

It hapend first time after installing two plugins - RealmBrowser and RealmPlugin.

Hmm. RealmBrowser installed. Probably WiFi issues.

Same with RealmPlugin.

Ok. So, somehow Alcatraz just nullified  "Deployment Target" and that's all.

Can't reproduce. Closed.
