### ISSUE TITLE
Add support for Xcode 7.3 beta 3

### ISSUE THREAD

**Issue by bastienvinh** [alcatraz/Alcatraz#425]
Hello,

Can you add support for this version please ?

Thank you.

**Comment by alanhamlett** [comment]
7.3 beta 3 is already supported with 316b99d6ba22e426a7ee14940693ed028e522782 because the DVTPlugInCompatibilityUUIDs are the same:

https://wakatime.com/api/v1/xcode_releases

**Comment by bastienvinh** [comment]
Okay I found it. Thank to you. The DVTPlugInCompatibilityUUIDs was not added to my Info.pl.
Maybe I failed to remove the cache files.

Thank you

**Comment by crenwick** [comment]
@alanhamlett -- In the link the `Xcode 7.3 Beta4` has the property `"dvt_uuid": null`. Is that normal / could that be messing with my builds (which are currently failing with Beta 4).

This is my first time digging into this, so I'm not sure if the fault is on my end, on apples end (until they provide a uuid?), or a bug here.

**Comment by alanhamlett** [comment]
@crenwick from #427 looks like it will be fixed when a new version of Alctraz is released.

**Comment by crenwick** [comment]
Oh, nice. I didn't see that issue. Thanks!
