### ISSUE TITLE
Installation error: too few X's

### ISSUE THREAD

**Issue by genedelisa** [alcatraz/Alcatraz#426]
curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh

mktemp: too few X's in template 'com.mneorr.Alcatraz'

running with -xv yields this output:

/bin/sh

set -euo pipefail
+ set -euo pipefail

DOWNLOAD_URI=https://github.com/alcatraz/Alcatraz/releases/download/1.1.15/Alcatraz.tar.gz
+ DOWNLOAD_URI=https://github.com/alcatraz/Alcatraz/releases/download/1.1.15/Alcatraz.tar.gz
PLUGINS_DIR="${HOME}/Library/Application Support/Developer/Shared/Xcode/Plug-ins"
+ PLUGINS_DIR='/Users/gene/Library/Application Support/Developer/Shared/Xcode/Plug-ins'
XCODE_VERSION="$(xcrun xcodebuild -version | head -n1 | awk '{ print $2 }')"
xcrun xcodebuild -version | head -n1 | awk '{ print $2 }'
++ xcrun xcodebuild -version
++ head -n1
++ awk '{ print $2 }'
+ XCODE_VERSION=7.2
PLIST_PLUGINS_KEY="DVTPlugInManagerNonApplePlugIns-Xcode-${XCODE_VERSION}"
+ PLIST_PLUGINS_KEY=DVTPlugInManagerNonApplePlugIns-Xcode-7.2
BUNDLE_ID="com.mneorr.Alcatraz"
+ BUNDLE_ID=com.mneorr.Alcatraz
TMP_FILE="$(mktemp -t ${BUNDLE_ID})"
mktemp -t ${BUNDLE_ID}
++ mktemp -t com.mneorr.Alcatraz
mktemp: too few X's in template 'com.mneorr.Alcatraz'
+ TMP_FILE=

**Comment by genedelisa** [comment]
ps I fixed it like this:

TMP_FILE="$(mktemp -t ${BUNDLE_ID}.XXX)"

**Comment by jurre** [comment]
This is because you're using GNU system utils instead of the OSX default ones, see https://github.com/alcatraz/Alcatraz/pull/404 and https://github.com/alcatraz/Alcatraz/pull/421

**Comment by bfagundez** [comment]
download the file install.sh, change at line 10 `mktemp` for `/usr/bin/mktemp`, problem solved

**Comment by genedelisa** [comment]
As previously commented, I found a fix and posted it  right up there ^^^^

And sorry, I didn't have the time to go through 400 issues to find that someone else already mentioned this problem re GNU/OSX.

I had a problem and posted a solution.

**Comment by jurre** [comment]
Github has a pretty good search option that you could use next time. No need to go through 400 issues manually :)

I was referencing the previous discussion so you could read how we came to the decision not to fix this in ATZ.

**Comment by devxoul** [comment]
```console
$ export PATH=/usr/bin:$PATH`
$ curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh
```
