### ISSUE TITLE
Installed and doesn't show up

### ISSUE THREAD

**Issue by jel111** [alcatraz/Alcatraz#427]
I installed as stated but it doesn't show up in Xcode. I did a restart and relaunch but does not show up. When I prompt for version in Terminal after I install succesfully it says command not found.

**Comment by guillaume-algis** [comment]
Could you paste the output of 

    curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh

here, please?

Also, what do you mean by "When I prompt for version in Terminal" ?

**Comment by fbara** [comment]
I just tried the install on Xcode 7.3 beta (7D129n).  Here's the output of running the install script.

```
Last login: Sun Feb 14 11:19:22 on console
MacBook-Air:~ fbara$ curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh
2016-02-16 13:40:17.710 defaults[32137:994316] 
The domain/default pair of (/Users/fbara/Library/Preferences/com.apple.dt.Xcode, DVTPlugInManagerNonApplePlugIns-Xcode-7.3) does not exist
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   590    0   590    0     0   1127      0 --:--:-- --:--:-- --:--:--  1125
  0  106k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0x Alcatraz.xcplugin/
x Alcatraz.xcplugin/Contents/
x Alcatraz.xcplugin/Contents/Info.plist
x Alcatraz.xcplugin/Contents/MacOS/
x Alcatraz.xcplugin/Contents/Resources/
x Alcatraz.xcplugin/Contents/Resources/ATZPackageListTableCellView.nib
x Alcatraz.xcplugin/Contents/Resources/ATZPluginWindowController.nib
x Alcatraz.xcplugin/Contents/Resources/bitbucket_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/
x Alcatraz.xcplugin/Contents/Resources/eye_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/git_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/github_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/link_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings
x Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings
100  106k  100  106k    0     0  72921      0  0:00:01  0:00:01 --:--:-- 1378k

Alcatraz successfully installed!!1!🍻  Please restart your Xcode (7.3).
```

**Comment by jel111** [comment]
@fbara I get the same but it doesn't show up in the window menu drop down.

**Comment by jel111** [comment]
There prolly is a way through the command line to install packages but I thought the window menu would be much easier. Thanks for the reply @algis
Sorry I didn't get back to you earlier but been busy.

**Comment by guillaume-algis** [comment]
The UUID for Xcode 7.3b has been merged on January 12 (https://github.com/alcatraz/Alcatraz/commit/316b99d6ba22e426a7ee14940693ed028e522782) but no new version of Alactraz has been released since then.

@jurre @supermarin what do you think about releasing 1.2.0 ? This would also make the "blocked plugins" feature and a number of fixes "public".

Until the next release @fbara @jel111, you could clone Alcatraz and compile from `master`, this should make Alcatraz work w/ Xcode 7.3.

**Comment by fbara** [comment]
Thx, @guillaume-algis.  I'll give that a try but I'm still a bit of a beginner in that area so it might take me a few attempts to get it right.

**Comment by jurre** [comment]
> @jurre @supermarin what do you think about releasing 1.2.0 ? This would also make the "blocked plugins" feature and a number of fixes "public".

Yeah I'm :+1: on this. @kattrali @supermarin what about you?

**Comment by supermarin** [comment]
:shipit:

**Comment by fbara** [comment]
I restarted Xcode and it doesn't show up in the menu anymore.  I'll wait until 1.2.0 is released.

**Comment by kattrali** [comment]
Shipping is always the answer @jurre

**Comment by jurre** [comment]
I'll get on it tonight, feel free to beat me to it if anyone has time sooner

**Comment by jel111** [comment]
Wish I could @jurre. Thanks Buddy!

**Comment by paulofaria** [comment]
:shipit: :shipit: :shipit: 😊

**Comment by jurre** [comment]
New release should be ready, let me know if you run into any issues

**Comment by fbara** [comment]
Installed into 7.3b4 and it showed up with my plugins.  Thx!

**Comment by guillaume-algis** [comment]
@jurre as discussed in #414, I was expecting the new version to be `1.2.0`. Should I amend the changelog?

**Comment by jurre** [comment]
Crap, I totally forgot about that but you are right. I should amend the version

**Comment by guillaume-algis** [comment]
Shipped in 1.1.16.

**Comment by xster** [comment]
Have the same issue. 

```
$ curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh                                                                                                                                        (02-13 14:57:35)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   590    0   590    0     0   1003      0 --:--:-- --:--:-- --:--:--  1001
  0  107k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0x Alcatraz.xcplugin/
x Alcatraz.xcplugin/Contents/
x Alcatraz.xcplugin/Contents/Info.plist
x Alcatraz.xcplugin/Contents/MacOS/
x Alcatraz.xcplugin/Contents/Resources/
x Alcatraz.xcplugin/Contents/Resources/ATZPackageListTableCellView.nib
x Alcatraz.xcplugin/Contents/Resources/ATZPluginWindowController.nib
x Alcatraz.xcplugin/Contents/Resources/bitbucket_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/
x Alcatraz.xcplugin/Contents/Resources/eye_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/git_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/github_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/link_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings
x Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings
100  107k  100  107k    0     0  58027      0  0:00:01  0:00:01 --:--:--  411k

Alcatraz successfully installed!!1!🍻  Please restart your Xcode (8.2.1).
```

No menu item added.

**Comment by supermarin** [comment]
@xster have you unsigned / re-signed Xcode?

**Comment by afabbro** [comment]
I'm having the same issue, output looks identical to xster. 

How does one unsign/re-sign XCode? When I search I only find info on app signing so I'm not sure what you mean.

**Comment by guillaumealgis** [comment]
@afabbro see https://github.com/alcatraz/Alcatraz/issues/475

**Comment by jurre** [comment]
Word of warning, not trying to be a jerk, but if you don't know how to unsign Xcode, you probably shouldn't unsign Xcode.

**Comment by guillaumealgis** [comment]
@afabbro @jurre I second that 👍

**Comment by abuttlemur** [comment]
I am also experiencing this issue in XCode Version 8.2.1 (8C1002)
