### ISSUE TITLE
No search results | Invalid Certificate

### ISSUE THREAD

**Issue by zelinliu** [alcatraz/Alcatraz#428]
Installed through running XCode project. No search results. Tried to visit: http://raw.github.com/alcatraz/alcatraz-packages/master/packages.json and hit invalid certificate.

Also tried to run curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh and also hit invalid cert.

**Comment by guillaume-algis** [comment]
Could this be your ISP doing dodgy things with SSL trafic?
Where in the world are you located? I'm validating the cert fine from Paris, France.

**Comment by guillaume-algis** [comment]
@zelinliu any update on this?
Are you still hitting the invalid cert when installing?

**Comment by kattrali** [comment]
Closing this out; feel free to reopen if there is new information.
