### ISSUE TITLE
can't search anything content

### ISSUE THREAD

**Issue by devSC** [alcatraz/Alcatraz#434]
i have succeed install alcatraz plugin. but i can't install any other plugins.

the search result like this:
![image](https://cloud.githubusercontent.com/assets/6701462/13692374/efc2f968-e77b-11e5-946d-8bc1332e31b3.png)

but i can succeed to enter `https://raw.githubusercontent.com/alcatraz/alcatraz-packages/master/packages.json` link.

what's wrong ? 
Please help me.

**Comment by OdNairy** [comment]
You are searching in `color themes` instead of `plugins` category. Just switch to correct category.
If it helps - close the issue.

**Comment by devSC** [comment]
i know, but i can't search to any content on that day.

but it's work today.
