### ISSUE TITLE
Add support for Xcode 7.3

### ISSUE THREAD

**Issue by darrarski** [alcatraz/Alcatraz#438]
Unfortunately, #416 doesn't make Alcatraz working in Xcode 7.3 released today. Already tried reinstalling plugin, still not working.

**Comment by supermarin** [comment]
I'm not sure we shipped a new Alcatraz yet. have you tried building from `master`?

**Comment by darrarski** [comment]
Sure, I tried both installing with shell command provided on the website, and building & running latest source in Xcode 7.3.

**Comment by tdimeco** [comment]
Actually Apple just changed the final UUID of Xcode 7.3. The new one is `ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C`
