### ISSUE TITLE
Packages not loading in XCode 7.3

### ISSUE THREAD

**Issue by mattnedrich** [alcatraz/Alcatraz#441]
None of my packages seem to be loading in XCode 7.3. I've tried uninstalling/installing each package and restarting XCode, but haven't had any luck.

**Comment by alanhamlett** [comment]
Those packages must not have added support for Xcode 7.3 yet. Try [WakaTime](https://github.com/wakatime/xcode-wakatime), because I know that one has added support for 7.3 already.

**Comment by mattnedrich** [comment]
Interesting. I was unable to install XVim through Alcatraz, but was able to manually install it via the instructions provided here: https://github.com/XVimProject/XVim.

**Comment by guillaume-algis** [comment]
@mattnedrich this is because this plugin in particular uses a [custom Makefile to read Xcode's UDID](https://github.com/XVimProject/XVim/blob/master/Makefile#L24) and add it to its Info.plist file before installing.

**Comment by mattnedrich** [comment]
@guillaume-algis So some packages need to add Alcatraz specific installation support (outside of their individual support for XCode 7.3)?

**Comment by guillaume-algis** [comment]
@mattnedrich Nope, not at all. Alcatraz installs the plugins just fine, but Xcode won't load them if they don't include its UDID in their plist.

Manual install worked for XVim because running `make` adds the UDID of the current Xcode installation on you machine to the plugin's plist.

Hope I'm more clear :)

**Comment by mattnedrich** [comment]
Makes perfect sense. Looks like a PR is already open for that plugin (https://github.com/XVimProject/XVim/pull/935). I'll close this issue then. Thanks for the help.
