### ISSUE TITLE
Server aborted the SSL handshake 

### ISSUE THREAD

**Issue by MickeyHub** [alcatraz/Alcatraz#445]
much more than 10 times installation retry. but all failed with this info returned.

**Comment by alanhamlett** [comment]
Are you located behind The Great Firewall?

**Comment by MickeyHub** [comment]
Yeah, but I did it with Lantern running.

**Comment by guillaume-algis** [comment]
Probably the same issue as #428.

Unfortunately, I don't think there's much we can do if this caused by the Great Firewall...

**Comment by MickeyHub** [comment]
Maybe not attributed to GFW, I got the release archive by downloading manually using another iMac without any VPN. so may be attributed to the slow network speed.
