### ISSUE TITLE
Won't work after installing xcode 7.3 (7D175)

### ISSUE THREAD

**Issue by kywix** [alcatraz/Alcatraz#448]
Right after the installation Alcatraz stopped working all together.

I reinstalled Alcatraz after noticing that all plugins stopped working.
Some work for a little while then they stop working. Most don't even show up in the menus.

**Comment by jurre** [comment]
It's up to plugin maintainers to ensure their plugins work on the latest version of Xcode. There's little we can do about it

**Comment by kywix** [comment]
gotcha. thx!
