### ISSUE TITLE
Add code syntax coloring?

### ISSUE THREAD

**Issue by geuis** [alcatraz/Alcatraz#449]
Just found this project! I use xcode not only for Swift development, but also as a general editor for multiple languages including javascript, css, and python. One thing that has bugged me for years is that xcode doesn't have a way to assign syntax coloring to file extensions it doesn't recognize automatically. You have to do it individually for each file manually, and often the association doesn't get saved anyway.

Is there a way to correct this with a package from Alcatraz?

**Comment by jurre** [comment]
I don't know of such a package, but it sounds possible to me

**Comment by supermarin** [comment]
closing as this is not an Alcatraz issue
