### ISSUE TITLE
can not connect with it

### ISSUE THREAD

**Issue by vickmiller** [alcatraz/Alcatraz#450]
when i open up my terminal and write curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh,it show curl: (56) SSLRead() return error -9806,it show fail to connect before

**Comment by jurre** [comment]
Are you behind a firewall or anything that could block the connection?

**Comment by JanX2** [comment]
@jurre I believe we had that already. Probably the Great Firewall.

**Comment by supermarin** [comment]
unfortunately.
