### ISSUE TITLE
Mirror-Down screenshot display

### ISSUE THREAD

**Issue by MickeyHub** [alcatraz/Alcatraz#455]
I found the screenshot of the ACCodeSnippetRepository is mirror-down, but the source of the screenshot 
this plugin provided is right orientation.

![image](https://cloud.githubusercontent.com/assets/5426838/14489656/05593564-01a1-11e6-968f-9bf02907580b.png)

**Comment by jurre** [comment]
This seems like a duplicate of: https://github.com/alcatraz/Alcatraz/issues/402
