### ISSUE TITLE
There is none of plugins in package manager list page

### ISSUE THREAD

**Issue by xtxt** [alcatraz/Alcatraz#458]
![image](https://cloud.githubusercontent.com/assets/8444704/14730934/0883b082-087e-11e6-8a29-1f471de90094.png)
as above image, there is no plugins in package manager list, and it doesn't work when restart. Who can help me, thanks a lot! Xcode 7.3

**Comment by guillaume-algis** [comment]
Hello @xtxt, do you have any info printed in Console.app when launching Xcode / Alcatraz?

**Comment by xtxt** [comment]
Hello @guillaume-algis ,info in Console:"
2016-04-22 16:05:26.777 Xcode[2479:120152] Updating Repo: /Users/kevin-xutao/Library/Application Support/Alcatraz/Plug-ins/Alcatraz
git version 2.6.4 (Apple Git-63)
2016-04-22 16:05:31.911 Xcode[2479:120112] Git fetch output: 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
2016-04-22 16:05:32.598 Xcode[2479:120112] Git reset output: HEAD is now at c9f9bde updated install script for version 1.1.18
"

**Comment by guillaume-algis** [comment]
Hmmm not sure if that would be linked to the issue you're having with Alcatraz, but do you mind running `brew doctor`?

**Comment by xtxt** [comment]
It's resolved, click setting--->select 'Load Default Repository', then it works.Thank you! @guillaume-algis

**Comment by guillaume-algis** [comment]
Glad you could figure it out!
