### ISSUE TITLE
Bitbucket Url

### ISSUE THREAD

**Issue by poborp** [alcatraz/Alcatraz#466]
In the method "parseWebsiteTypeFromURLPath" from "ATZPackage.m" the correct url for bitbucket is "bitbucket.org", I think is better control both cases:

`} else if ([URLPath rangeOfString:@"bitbucket.com"].location != NSNotFound || [URLPath rangeOfString:@"bitbucket.org"].location != NSNotFound) {`

**Comment by guillaume-algis** [comment]
Fixed by #467.
