### ISSUE TITLE
Check whether Alcatraz is installed?

### ISSUE THREAD

**Issue by mattgabor** [alcatraz/Alcatraz#470]
Not necessarily an issue but I was wondering if there's a way to check whether Alcatraz is installed? which -s Alcatraz or which -s Alcatraz.xcplugin doesn't work.

**Comment by guillaume-algis** [comment]
Hi @mattgabor, you can simply check if the `Alcatraz.xcplugin` exists in Xcode's plugins directory:

    test -d ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin

Take note however that it doesn't cover the cases when Alcatraz being installed but not compatible with the current running Xcode version or when Xcode added Alcatraz to the skipped plugins list.
I encourage you to take a look at https://github.com/alcatraz/Alcatraz/blob/master/Scripts/install.sh to understand how we install Alcatraz. Let me know if you need more info.
