### ISSUE TITLE
swift plugin debug problem

### ISSUE THREAD

**Issue by intheway** [alcatraz/Alcatraz#472]
When I use swift language to develop plugin, I found that debugging is trouble.
The breakpoint step is out of oder, and I can't print the variable. you will get `variable not available` or `error: use of unresolved identifier 'xx'`. When the plugin crashed, I even can't know it's reason.

Does anybody meet these problems when using swift to develop xcode plugin?
Or how to solve these problems?
Many Thanks!

**Comment by jurre** [comment]
This doesn't look like an issue with Alcatraz, you could try reaching out to other plugin develops on our gitter chat: https://gitter.im/alcatraz/Alcatraz
