### ISSUE TITLE
Install plug-in hardly & xvim couldn't work

### ISSUE THREAD

**Issue by SSCedric** [alcatraz/Alcatraz#474]
I try to install xvim use alcatraz many time. I got it before i want to give up.

Then i face another trouble that xvii couldn't work.
(I installed  gitdiff and it work)
(I check its page in github and follow the realme file then it worked)

**Comment by guillaume-algis** [comment]
Hi @SSCedric, thank you for the report.

Could you try reinstalling the plugin with Alcatraz, and paste here the Xcode logs found in Console.app?
This would help us understand exactly what is wrong in order to fix it.

Thank you!
