### ISSUE TITLE
Xcode setup reset?

### ISSUE THREAD

**Issue by sabertoothPaste** [alcatraz/Alcatraz#477]
Everytime I press Command+Q to quit Xcode and reopen it, the Xcode will show "Unexpected code bundles" alert , and the color&font will be reset to Basic too.

**Comment by guillaume-algis** [comment]
Which Xcode version are you using?

**Comment by sabertoothPaste** [comment]
It's the latest  v7.3.1, and I  install the plugin by running "curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh" in terminal

**Comment by guillaume-algis** [comment]
Are other Xcode preferences lost upon restart too?

I'm thinking you might have a permission problem on the Xcode preferences plist `~/Library/Preferences/com.apple.dt.Xcode.plist`.

What's the output of the following command on your machine?

    ❯ ls -l ~/Library/Preferences/com.apple.dt.*
    -rw-------  1 guillaume  staff   445K  1 avr 14:37 /Users/guillaume/Library/Preferences/com.apple.dt.Instruments.plist
    -rw-------  1 guillaume  staff   1,5K 14 avr 15:24 /Users/guillaume/Library/Preferences/com.apple.dt.Xcode.Playground.plist
    -rw-------  1 guillaume  staff   136K 23 jui 11:53 /Users/guillaume/Library/Preferences/com.apple.dt.Xcode.plist
    -rw-------  1 guillaume  staff   2,8K 15 jui 11:08 /Users/guillaume/Library/Preferences/com.apple.dt.xcodebuild.plist

**Comment by sabertoothPaste** [comment]
No, the custom theme still exist, it just reset to Basic.
I tried install the plugin by running the project downloaded from the git hub, and it works fine
Here is the output:
Zst:~ Sabertooth$ ls -l ~/Library/Preferences/com.apple.dt.*
-rw-------  1 Sabertooth  staff   58943  6  3 19:30 /Users/zhangshitong/Library/Preferences/com.apple.dt.Instruments.plist
-rw-------  1 Sabertooth  staff  504128  6 23 19:35 /Users/zhangshitong/Library/Preferences/com.apple.dt.Xcode.plist
-rw-------  1 Sabertooth  staff     306  6 23 19:26 /Users/zhangshitong/Library/Preferences/com.apple.dt.xcodebuild.plist

**Comment by sabertoothPaste** [comment]
I just tried the 

> curl -fsSL
command, and the alert didn't occured
