### ISSUE TITLE
Xcode 8 beta 1: install Alcatraz fail

### ISSUE THREAD

**Issue by yueqianzhang** [alcatraz/Alcatraz#481]
### Goals

Install Alcatraz with Xcode 8 Beta 1

### Expected Results

The package manager should successfully Install

### Actual Results

Install fails to build In Terminal with this error
`xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH`

### Steps to Reproduce

Terminal input: `curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh` 

### Version Info

Alcatraz version: latest

Xcode version: 8.0 Beta 1

OSX version:  OS X 10.11.6

**Comment by jurre** [comment]
Please see: https://github.com/alcatraz/Alcatraz/issues/475
