### ISSUE TITLE
loss the Alcatraz for Xcode8.0

### ISSUE THREAD

**Issue by andy90s** [alcatraz/Alcatraz#485]
😢  why I can't find the Alcatraz for the window ，and  I had reinstalled it.

**Comment by klkucan** [comment]
not support yet, i guess

**Comment by RobertGummesson** [comment]
Plug-ins are not and will not be supported in Xcode 8. See [#475](https://github.com/alcatraz/Alcatraz/issues/475#issuecomment-246916123).
