### ISSUE TITLE
Unable to locate window->Package manager in Xcode 7.3

### ISSUE THREAD

**Issue by saurabhbsd** [alcatraz/Alcatraz#489]
I have cloned Alcatraz on my mac Air. To proceed with second step, I'm unable to find Package Manager in Window menu of Xcode 7.3.

**Comment by alanhamlett** [comment]
You can't just clone Alcatraz, you have to run the installation command in a Terminal:

`curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh`

https://github.com/alcatraz/Alcatraz#installation

**Comment by guillaumealgis** [comment]
Thanks @alanhamlett :)
