### ISSUE TITLE
Not working in Xcode8

### ISSUE THREAD

**Issue by ixp9891** [alcatraz/Alcatraz#491]
Xcode8 install the plug-in fail

**Comment by dbarros** [comment]
Try restarting your Mac. Has worked for some people.

**Comment by imqiuhang** [comment]
i find this is useful  http://www.jianshu.com/p/dc2fc2a680fc  succeed!

**Comment by R0cKET** [comment]
https://github.com/alcatraz/Alcatraz/issues/73

**Comment by jurre** [comment]
Xcode 8 does not support loading plugins out of the box anymore.

Please see #475 for more info.
