### ISSUE TITLE
Can't install Alcatraz

### ISSUE THREAD

**Issue by MaddDogg0001** [alcatraz/Alcatraz#492]
Hi !

I've trying install your plugin manager, but here is the thing, I've been trying with command line (the one on the website, and one of a previous issue), nothing happens.
So I remove everything with command line you give, and I've downloaded the project from this repository, I ran it in Xcode, rebooted it, it shows me the pop-up for loading the bundle, I loaded it, I've been waiting, but still nothing...

I'm on Xcode 8, and I still don't have the package manager :(

Could you help me ?

**Comment by ksteigerwald** [comment]
https://github.com/inket/update_xcode_plugins

You might need to restart. I had some trouble with this approach yesterday. I am trying it again on my home laptop. It will create a copy of XCode and unsign it to allow plugins to load. Use at your own risk

**Comment by mhmmtucan** [comment]
Have a look at this topic: https://github.com/alcatraz/Alcatraz/issues/475

**Comment by jurre** [comment]
Loading plugins in Xcode 8 is no longer supported by Apple. See #475 for more info
