### ISSUE TITLE
Does not appear in Windows in Xcode 8.0

### ISSUE THREAD

**Issue by CyberMew** [alcatraz/Alcatraz#494]
First time user, after executing `curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh` in Terminal, it says successful but I don't see it.

**Comment by RobertGummesson** [comment]
It's not supported in Windows, only OS X. 

Just kidding, see [#475](https://github.com/alcatraz/Alcatraz/issues/475).
