### ISSUE TITLE
instal a plugin from git failed on mac

### ISSUE THREAD

**Issue by leeyoungalias** [alcatraz/Alcatraz#504]
My mac have a little problem,i need to compile git by my self ,i prefix to another path,but look like when install a plugin from git it use a command like
```
/usr/bin/git -balabalbala
```
And it's down.I make sure it's because use the wrong git execute binary.
why not just
```
git -balabala
```

**Comment by tanpengsccd** [comment]
this not a issue  of Alcatraz....
may be U just need to  set alias  for for your bash/zsh.
