### ISSUE TITLE
Installed Alcatraz but only got a black bar that I can't remove (even after uninstalling the plugin)

### ISSUE THREAD

**Issue by SimonFearby** [alcatraz/Alcatraz#509]
I Installed Alcatraz on XCode 8.2.1 but only received a black bar that appears to the right of the Identity Pane.

I installed via: curl -fsSL > https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh

I uninstalled Alcatraz via the following but XCode still has a black bar that i cant remove.

>Delete the plugin:
>rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
>Remove all cached data:
>rm -rf ~/Library/Application\ Support/Alcatraz

How can I remove the black bar from XCode that wants to be Alcatraz,

**Comment by SimonFearby** [comment]
"defaults delete com.apple.dt.Xcode" does not work :(

**Comment by SimonFearby** [comment]
It might be a good idea to take down http://alcatraz.io/ or warn of issues with XCode 8.x

**Comment by jurre** [comment]
I'm not sure if the black bar is related to Alcatraz, you need to unsign xcode for it to even ever load the code. Can you post a screenshot?

**Comment by supermarin** [comment]
closing as this shouldn't be Alcatraz related. will reopen if proven otherwise
