### ISSUE TITLE
Xcode 8 and alcatraz.io 

### ISSUE THREAD

**Issue by mmontag** [alcatraz/Alcatraz#517]
Can you update alcatraz.io with the prominent warning "Please note that Alcatraz is not supported by Xcode 8."

The first two steps everyone tries: 

1) Visit alcatraz.io
2) Paste shell command into terminal

Neither one of these things mentions incompatibility with Xcode 8 and that seems like a big oversight. But thanks for all the prominent warnings over here on Github.

**Comment by guillaumealgis** [comment]
Thank you for the feedback @mmontag, I agree this is a problem !

I opened #518 to fix this.

Thanks again :)
