### ISSUE TITLE
Xcode 9?

### ISSUE THREAD

**Issue by euforic** [alcatraz/Alcatraz#522]
Has anything changed with Xcode 9 to allow for things to work now? I came across this https://sympli.io/downloads/xcode and it seems like plugins should be working again?

Xcode 8 isn't working? See https://github.com/alcatraz/Alcatraz/issues/475

**Comment by guillaumealgis** [comment]
AFAIK, nothing changed. The plugin you're linking is distributed with an installer, which probably unsign Xcode.

**Comment by cprovatas** [comment]
@euforic I don't think sympli is using Alcatraz at all to load the plugin.  It looks the plugin installs an external daemon on your system that controls Xcode somehow (perhaps by hooking into LLDB)
