### ISSUE TITLE
xcode 9.2 Can you use it?

### ISSUE THREAD

**Issue by YHqihuan** [alcatraz/Alcatraz#524]
xcode 9.2 Can you use it?

**Comment by manmanking** [comment]
install sudo gem install update_xcode_plugins
and 
update_xcode_plugins
this plugin is working

**Comment by mike-lischke** [comment]
Not for me (XCode 9.3.1). Also `update_xcode_plugins` didn't help, the menu entry simply doesn't appear (though XCode asked me to load the bundle, which I agreed on).

**Comment by jurre** [comment]
It is not supported on iOS 9, it requires some hacks to unsign Xcode that we don't support.

**Comment by mike-lischke** [comment]
So why keeping this project up? You can delete it now to avoid having people trying for quite some time to get it running while looking for a solution.

**Comment by alanhamlett** [comment]
It's still being used by people who unsigned their Xcode.

For example, #498 and https://wakatime.com/xcode.

**Comment by guillaumealgis** [comment]
The very first line of the README states clearly that Alcatraz was designed for Xcode **7**. A few lines down we added a statement in bold that Xcode 8+ is not supported, with a link to the issue where this compatibility problem is discussed.

Some people still find Alcatraz useful, I don't see why we should delete it.

**Comment by mike-lischke** [comment]
I see, I should have added the `<irony>` tag. First it is stated that this project doesn't support the only remaining solution (unsigning XCode) and next that solution is brought up as reason to keep this project up. Do you see the irony now?

**Comment by guillaumealgis** [comment]
@mike-lischke I think it all comes down to a communication problem, we should maybe do a better job at indicating the current state of the project.

I think @jurre was talking about the maintainers position on unsigning Xcode when he said "we don't support [it]". But Alcatraz **does work** once Xcode is unsigned (I haven't tested it myself, but others do use it).
