### ISSUE TITLE
xcode9.2 报错

### ISSUE THREAD

**Issue by wzj583585700** [alcatraz/Alcatraz#526]
Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Operation timed out

**Comment by alanhamlett** [comment]
Great firewall?

**Comment by shenerJ** [comment]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Symbol not found: __T0SPyxGs8_PointersWP
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection

**Comment by guillaumealgis** [comment]
@shenerJ this is a problem with the InjectionIII app (look a the paths). It has nothing to do with Alcatraz.
